version: '3.8'
services:
  document:
    build:
      dockerfile: docker/Dockerfile
      context: .
    container_name: bakerdh/uncannyvalley:knit
    image: bakerdh/uncannyvalley:knit
    volumes:
      - .:/home/rstudio
    environment:
      DISABLE_AUTH: 'true'
    working_dir: /home/rstudio
    command: make document-docker
